# Generated by Django 6.0.5 on 2026-05-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionrecord",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emissions.company",
            ),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emissions.datasource",
            ),
        ),
    ]
