# Generated by Django 6.0.5 on 2026-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0002_emissionrecord_company_emissionrecord_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionrecord",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
